

name: Maven-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Step 1 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Step 2 - Set up a cache for maven
      uses: actions/cache@v2
      with:
       path: ~/.m2
       key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
       restore-keys: ${{ runner.os }}-m2
       
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml


    - name: Step 4 - List the current directory
      run: ls

    - name: Step 5 - The target folder contains;
      run: |
        cd target
        ls

    - name: Step 6 - List the Environmental variables
      run: env

    
        
   
  
    
